# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2026'
email: rcai92130@gmail.com
full_name: Robin Cai
gh_action_docs_preview: false
gh_action_pypi: false
github_org: cair2015
license: MIT
project_description: An ontology-first LinkML model for the Reactome data model.
project_name: reactome-ontology
project_slug: reactome_ontology

